name: crescent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.3
  flutter_inner_shadow: 0.0.1
  shelf: ^1.4.1
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  shelf_plus: ^1.9.2
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.4
  mysql1: ^0.20.0
  shared_preferences: 2.0.15
  # wayland: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/CrescentLongLogo.svg

  fonts:
    - family: Jomolhari
      fonts:
        - asset: assets/fonts/Jomolhari-Regular.ttf
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans.ttf
